### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by molu-ggg** [SHI-Labs/OneFormer#99]
In accordance with the PyTorch 
environment and CUDA version you provided, I encountered this error. How can I resolve it? Thank you !
`RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

‘’’
Traceback (most recent call last):
  File "train_net.py", line 435, in <module>
    launch(
  File "/home/data/agqing/OneFormer-main/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_net.py", line 416, in main
    res = Trainer.test(cfg, model)
  File "train_net.py", line 366, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/data/agqing/OneFormer-main/detectron2/detectron2/evaluation/evaluator.py", line 158, in inference_on_dataset
    outputs = model(inputs)
  File "/home/hya4000/anaconda3/envs/oneformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/data/agqing/OneFormer-main/oneformer/oneformer_model.py", line 277, in forward
    tasks = self.task_mlp(tasks.float())
  File "/home/hya4000/anaconda3/envs/oneformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/data/agqing/OneFormer-main/oneformer/modeling/transformer_decoder/oneformer_transformer_decoder.py", line 222, in forward
    x = F.relu(layer(x)) if i < self.num_layers - 1 else layer(x)
  File "/home/hya4000/anaconda3/envs/oneformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hya4000/anaconda3/envs/oneformer/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/hya4000/anaconda3/envs/oneformer/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

‘’’

**Comment by ShenhaoZhu** [comment]
I solved the issue by updating pytorch to 1.12.1

**Comment by cz-cz** [comment]
hi，i tried a way from [csdn-blog](https://blog.csdn.net/CODE_RabbitV/article/details/140009596)
just `unset LD_LIBRARY_PATH`
and then when running demo ,i had another error
`AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations`
i just change all  `np.bool`  in code to `bool`
now, i can run the demo and got result images!!!
